### ISSUE TITLE
RISCV64: polyvec_basemul_acc_montgomery smashes the stack

### ISSUE THREAD

**Issue by smuellerDD** [Ji-Peng/PQRV#1]
First of all, thanks a lot for your development! I have added the IM/IMB of Keccak to my crypto library [1]. Performance on a Spacemit X60 is stellar (see [2] for some hints).

I also added ML-KEM RISCV64 ASM support based on your code, see [3].

However, I spotted an issue that I am not sure how resolve it: The function polyvec_basemul_acc_montgomery smashes the stack when using your straight implementation. I had to add the buffer [4] after the r_double scratch space to get rid of the stack smashing. Note, I traced the issue down the issue to the function [5] which apart from the declaration and symbol name is unchanged to yours.

Do you have any idea on what it could be? Note, the buffer must be at least 128 int32_t blocks. With 127 it still incurs a stack smasher.

[1] https://github.com/smuellerDD/leancrypto

[2] https://github.com/smuellerDD/leancrypto/commit/b0ace8a886338ca86907f66606b425fc51bf8a29

[3] https://github.com/smuellerDD/leancrypto/commit/3caa605a3386583cd79f083ddaa3958cb454acb2

[4] https://github.com/smuellerDD/leancrypto/blob/master/ml-kem/src/riscv64/kyber_polyvec_riscv.h#L103

[5] https://github.com/smuellerDD/leancrypto/blob/master/ml-kem/src/riscv64/ntt_dualissue_plant_rv64im.S#L907

**Comment by Ji-Peng** [comment]
Thank you for your feedback.  

At first glance, I suspected that my code might have caused an out-of-bounds read on `poly_double`. However, after carefully examining the assembly code, it seems there is no such issue.  

Could you provide a minimal project that can reproduce this problem? This would greatly facilitate troubleshooting and debugging.  

Additionally, I noticed that your project does not seem to explicitly specify the compilation options for `ntt_dualissue_plant_rv64im.S`. In contrast, `hash/src/meson.build` does include explicit compilation options. If `ntt_dualissue_plant_rv64im.S` is compiled with the `rv32im` option, it might result in potential errors.

**Comment by smuellerDD** [comment]
Am Sonntag, 24. November 2024, 13:40:10 Mitteleuropäische Normalzeit schrieb 
Ji-Peng:

Hi Ji-Peng,

> Thank you for your feedback.
> 
> At first glance, I suspected that my code might have caused an out-of-bounds
> read on `poly_double`. However, after carefully examining the assembly
> code, it seems there is no such issue.
> 
> Could you provide a minimal project that can reproduce this problem? This
> would greatly facilitate troubleshooting and debugging.

I think it is already there:

1. update cross-compile/riscv64-gcc13-suse.txt to point to your cross 
compilers

2. meson setup --cross-file cross-compile/riscv64-gcc13-suse.txt build

3. meson compile -C build

4. now you have a standalone application with the issue: build/ml-kem/tests/
kyber_kem_tester_common - simply copy this file over and execute.

> 
> Additionally, I noticed that your project does not seem to explicitly
> specify the compilation options for `ntt_dualissue_plant_rv64im.S`. In
> contrast, `hash/src/meson.build` does include explicit compilation options.
> If `ntt_dualissue_plant_rv64im.S` is compiled with the `rv32im` option, it
> might result in potential errors.

I have fixed that, thanks for pointing out. But it is of no help.


Ciao
Stephan

**Comment by Ji-Peng** [comment]
I followed the steps mentioned above, but the resulting executable file does not run on my CanMV-K230 board. It seems that only executables compiled with the `-static` option can run on this board.  

Fortunately, I have a Milk-V Jupiter motherboard with a SpaceMIT X60 SoC. However, I still need to purchase a case and power supply to assemble it into a mini PC. It will take me approximately 3-5 days to complete the setup. Once it’s ready, I will attempt to reproduce the issue. Please wait for my update.

**Comment by Ji-Peng** [comment]
The file `ntt_dualissue_plant_rv64im.S` requires the addition of a `ret` instruction after line 1032. I spent a long time debugging the program with GDB before discovering this error. It was an extremely frustrating experience.

**Comment by smuellerDD** [comment]
My sincere apologies to add such unnecessary issue. It is fixed now.
